### ISSUE TITLE
Issue to be resolved for the Display text.

### ISSUE THREAD

**Issue by atharvagadkari05** [atharvagadkari05/typingGAME#1]
The main Text which comes under the ID: '#current-word'  can be copied and pasted in the input box.

![image](https://user-images.githubusercontent.com/74293435/116529871-04758380-a8fb-11eb-9411-3b0b935afc3a.png)

We have to work under this issue and resolve this bug so that the user cannot copy that word and paste it into the input box.

Feel free to comment!!!!!!

**Comment by bakhosRachwan** [comment]
in your css file call the #current-word and put these lines in to override the select option.
#current-word { 
-webkit-user-select: none;
-webkit-touch-callout: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
}

**Comment by atharvagadkari05** [comment]
Thanks, @bakhosRachwan

**Comment by bakhosRachwan** [comment]
I see this issue is still open, are you still having a problem with the select?

**Comment by atharvagadkari05** [comment]
This issue has been resolved.
